spring:
  datasource:
    url: jdbc:mysql://120.76.224.243:3306/childgarden_test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mappers/*.xml
